name: Job Tracker Automation
on:
  schedule:
    - cron: '0 0 * * *' # Runs every night at midnight
  workflow_dispatch:      # Allows you to click a button to run it manually

jobs:
  run-tracker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run Script
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          SERP_API_KEY: ${{ secrets.SERP_API_KEY }}
        run: python main.py
